embedding_sizes = {}

embedding_sizes["application_train"] = {'NAME_CONTRACT_TYPE': 2,
                                        'CODE_GENDER': 2,
                                        'FLAG_OWN_CAR': 2,
                                        'FLAG_OWN_REALTY': 2,
                                        'FONDKAPREMONT_MODE': 3,
                                        'HOUSETYPE_MODE': 2,
                                        'WALLSMATERIAL_MODE': 3,
                                        'EMERGENCYSTATE_MODE': 2,
                                        'ORGANIZATION_TYPE': 10,
                                        'OCCUPATION_TYPE': 5,
                                        'WEEKDAY_APPR_PROCESS_START': 3,
                                        'NAME_TYPE_SUITE': 3,
                                        'NAME_INCOME_TYPE': 3,
                                        'NAME_EDUCATION_TYPE': 2,
                                        'NAME_FAMILY_STATUS': 3,
                                        'NAME_HOUSING_TYPE': 3}

embedding_sizes["bureau"] = {'CREDIT_ACTIVE': 3,
                             'CREDIT_CURRENCY': 3,
                             'CREDIT_TYPE': 5}

embedding_sizes["previous_application"] = {"NAME_CONTRACT_TYPE": 2,
                                            "NAME_YIELD_GROUP": 2,
                                            "PRODUCT_COMBINATION": 5,
                                            "NAME_SELLER_INDUSTRY": 3,
                                            "NAME_PAYMENT_TYPE": 2,
                                            "CODE_REJECT_REASON": 3,
                                            "NAME_TYPE_SUITE": 3,
                                            "NAME_CLIENT_TYPE": 2,
                                            "NAME_GOODS_CATEGORY": 5,
                                            "NAME_PORTFOLIO": 2,
                                            "NAME_PRODUCT_TYPE": 2,
                                            "CHANNEL_TYPE": 2,
                                            "NAME_CASH_LOAN_PURPOSE": 5,
                                            "NAME_CONTRACT_STATUS": 2,
                                            "FLAG_LAST_APPL_PER_CONTRACT": 2,
                                            "WEEKDAY_APPR_PROCESS_START": 3}

col_classes = {}

col_classes["previous_application"] = {'numeric' : ['SK_ID_CURR',
                                                    'SK_ID_PREV',
                                                    'AMT_ANNUITY',
                                                    'AMT_APPLICATION',
                                                    'AMT_CREDIT',
                                                    'AMT_DOWN_PAYMENT',
                                                    'AMT_GOODS_PRICE',
                                                    'HOUR_APPR_PROCESS_START',
                                                    'NFLAG_LAST_APPL_IN_DAY',
                                                    'RATE_DOWN_PAYMENT',
                                                    'RATE_INTEREST_PRIMARY',
                                                    'RATE_INTEREST_PRIVILEGED',
                                                    'DAYS_DECISION',
                                                    'SELLERPLACE_AREA',
                                                    'CNT_PAYMENT',
                                                    'DAYS_FIRST_DRAWING',
                                                    'DAYS_FIRST_DUE',
                                                    'DAYS_LAST_DUE_1ST_VERSION',
                                                    'DAYS_LAST_DUE',
                                                    'DAYS_TERMINATION',
                                                    'NFLAG_INSURED_ON_APPROVAL'],
                                      'categorical' : ['NAME_CONTRACT_TYPE',
                                                        'NAME_YIELD_GROUP',
                                                        'PRODUCT_COMBINATION',
                                                        'NAME_SELLER_INDUSTRY',
                                                        'NAME_PAYMENT_TYPE',
                                                        'CODE_REJECT_REASON',
                                                        'NAME_TYPE_SUITE',
                                                        'NAME_CLIENT_TYPE',
                                                        'NAME_GOODS_CATEGORY',
                                                        'NAME_PORTFOLIO',
                                                        'NAME_PRODUCT_TYPE',
                                                        'CHANNEL_TYPE',
                                                        'NAME_CASH_LOAN_PURPOSE',
                                                        'NAME_CONTRACT_STATUS',
                                                        'FLAG_LAST_APPL_PER_CONTRACT',
                                                        'WEEKDAY_APPR_PROCESS_START']}

col_classes["bureau"] = {'numeric' : ['SK_ID_CURR',
                                                    'SK_ID_BUREAU',
                                                    'DAYS_CREDIT',
                                                    'CREDIT_DAY_OVERDUE',
                                                    'DAYS_CREDIT_ENDDATE',
                                                    'DAYS_ENDDATE_FACT',
                                                    'AMT_CREDIT_MAX_OVERDUE',
                                                    'CNT_CREDIT_PROLONG',
                                                    'AMT_CREDIT_SUM',
                                                    'AMT_CREDIT_SUM_DEBT',
                                                    'AMT_CREDIT_SUM_LIMIT',
                                                    'AMT_CREDIT_SUM_OVERDUE',
                                                    'DAYS_CREDIT_UPDATE',
                                                    'AMT_ANNUITY'],
                                     'categorical':['CREDIT_ACTIVE',
                                                    'CREDIT_CURRENCY',
                                                    'CREDIT_TYPE']}
col_classes["credit_card_balance"] = {'numeric' : ['SK_ID_PREV',
                                                   'SK_ID_CURR',
                                                   'MONTHS_BALANCE',
                                                   'AMT_BALANCE',
                                                   'AMT_CREDIT_LIMIT_ACTUAL',
                                                   'AMT_DRAWINGS_ATM_CURRENT',
                                                   'AMT_DRAWINGS_CURRENT',
                                                   'AMT_DRAWINGS_OTHER_CURRENT',
                                                   'AMT_DRAWINGS_POS_CURRENT',
                                                   'AMT_INST_MIN_REGULARITY',
                                                   'AMT_PAYMENT_CURRENT',
                                                   'AMT_PAYMENT_TOTAL_CURRENT',
                                                   'AMT_RECEIVABLE_PRINCIPAL',
                                                   'AMT_RECIVABLE',
                                                   'AMT_TOTAL_RECEIVABLE',
                                                   'CNT_DRAWINGS_ATM_CURRENT',
                                                   'CNT_DRAWINGS_CURRENT',
                                                   'CNT_DRAWINGS_OTHER_CURRENT',
                                                   'CNT_DRAWINGS_POS_CURRENT',
                                                   'CNT_INSTALMENT_MATURE_CUM',
                                                   'SK_DPD',
                                                   'SK_DPD_DEF'],
                                      'categorical': ['NAME_CONTRACT_STATUS']}
col_classes["simple_model"] = {'numeric': ['EXT_SOURCE_1',
                                           'EXT_SOURCE_2',
                                           'EXT_SOURCE_3']}
col_classes["application_train"] = {'target':['TARGET'],
                                    'numeric': ['SK_ID_CURR',
                                                'CNT_CHILDREN',
                                                'AMT_INCOME_TOTAL',
                                                'AMT_CREDIT',
                                                'AMT_ANNUITY',
                                                'AMT_GOODS_PRICE',
                                                'REGION_POPULATION_RELATIVE',
                                                'DAYS_BIRTH',
                                                'DAYS_EMPLOYED',
                                                'DAYS_REGISTRATION',
                                                'DAYS_ID_PUBLISH',
                                                'OWN_CAR_AGE',
                                                'FLAG_MOBIL',
                                                'FLAG_EMP_PHONE',
                                                'FLAG_WORK_PHONE',
                                                'FLAG_CONT_MOBILE',
                                                'FLAG_PHONE',
                                                'FLAG_EMAIL',
                                                'HOUR_APPR_PROCESS_START',
                                                'REG_REGION_NOT_LIVE_REGION',
                                                'REG_REGION_NOT_WORK_REGION',
                                                'LIVE_REGION_NOT_WORK_REGION',
                                                'REG_CITY_NOT_LIVE_CITY',
                                                'REG_CITY_NOT_WORK_CITY',
                                                'LIVE_CITY_NOT_WORK_CITY',
                                                'EXT_SOURCE_1',
                                                'EXT_SOURCE_2',
                                                'EXT_SOURCE_3',
                                                'APARTMENTS_AVG',
                                                'BASEMENTAREA_AVG',
                                                'YEARS_BEGINEXPLUATATION_AVG',
                                                'YEARS_BUILD_AVG',
                                                'COMMONAREA_AVG',
                                                'ELEVATORS_AVG',
                                                'ENTRANCES_AVG',
                                                'FLOORSMAX_AVG',
                                                'FLOORSMIN_AVG',
                                                'LANDAREA_AVG',
                                                'LIVINGAPARTMENTS_AVG',
                                                'LIVINGAREA_AVG',
                                                'NONLIVINGAPARTMENTS_AVG',
                                                'NONLIVINGAREA_AVG',
                                                'APARTMENTS_MODE',
                                                'BASEMENTAREA_MODE',
                                                'YEARS_BEGINEXPLUATATION_MODE',
                                                'YEARS_BUILD_MODE',
                                                'COMMONAREA_MODE',
                                                'ELEVATORS_MODE',
                                                'ENTRANCES_MODE',
                                                'FLOORSMAX_MODE',
                                                'FLOORSMIN_MODE',
                                                'LANDAREA_MODE',
                                                'LIVINGAPARTMENTS_MODE',
                                                'LIVINGAREA_MODE',
                                                'NONLIVINGAPARTMENTS_MODE',
                                                'NONLIVINGAREA_MODE',
                                                'APARTMENTS_MEDI',
                                                'BASEMENTAREA_MEDI',
                                                'YEARS_BEGINEXPLUATATION_MEDI',
                                                'YEARS_BUILD_MEDI',
                                                'COMMONAREA_MEDI',
                                                'ELEVATORS_MEDI',
                                                'ENTRANCES_MEDI',
                                                'FLOORSMAX_MEDI',
                                                'FLOORSMIN_MEDI',
                                                'LANDAREA_MEDI',
                                                'LIVINGAPARTMENTS_MEDI',
                                                'LIVINGAREA_MEDI',
                                                'NONLIVINGAPARTMENTS_MEDI',
                                                'NONLIVINGAREA_MEDI',
                                                'OBS_30_CNT_SOCIAL_CIRCLE',
                                                'DEF_30_CNT_SOCIAL_CIRCLE',
                                                'OBS_60_CNT_SOCIAL_CIRCLE',
                                                'DEF_60_CNT_SOCIAL_CIRCLE',
                                                'DAYS_LAST_PHONE_CHANGE',
                                                'TOTALAREA_MODE',
                                                'FLAG_DOCUMENT_2',
                                                'CNT_FAM_MEMBERS',
                                                'REGION_RATING_CLIENT',
                                                'REGION_RATING_CLIENT_W_CITY',
                                                'FLAG_DOCUMENT_3',
                                                'FLAG_DOCUMENT_4',
                                                'FLAG_DOCUMENT_5',
                                                'FLAG_DOCUMENT_6',
                                                'FLAG_DOCUMENT_7',
                                                'FLAG_DOCUMENT_8',
                                                'FLAG_DOCUMENT_9',
                                                'FLAG_DOCUMENT_10',
                                                'FLAG_DOCUMENT_11',
                                                'FLAG_DOCUMENT_12',
                                                'FLAG_DOCUMENT_13',
                                                'FLAG_DOCUMENT_14',
                                                'FLAG_DOCUMENT_15',
                                                'FLAG_DOCUMENT_16',
                                                'FLAG_DOCUMENT_17',
                                                'FLAG_DOCUMENT_18',
                                                'FLAG_DOCUMENT_19',
                                                'FLAG_DOCUMENT_20',
                                                'FLAG_DOCUMENT_21',
                                                'AMT_REQ_CREDIT_BUREAU_HOUR',
                                                'AMT_REQ_CREDIT_BUREAU_DAY',
                                                'AMT_REQ_CREDIT_BUREAU_WEEK',
                                                'AMT_REQ_CREDIT_BUREAU_MON',
                                                'AMT_REQ_CREDIT_BUREAU_QRT',
                                                'AMT_REQ_CREDIT_BUREAU_YEAR'
                                                ],
                                   'categorical' : ['NAME_CONTRACT_TYPE',
                                                    'CODE_GENDER',
                                                    'FLAG_OWN_CAR',
                                                    'FLAG_OWN_REALTY',
                                                    'FONDKAPREMONT_MODE',
                                                    'HOUSETYPE_MODE',
                                                    'WALLSMATERIAL_MODE',
                                                    'EMERGENCYSTATE_MODE',
                                                    'ORGANIZATION_TYPE',
                                                    'OCCUPATION_TYPE',
                                                    'WEEKDAY_APPR_PROCESS_START',
                                                    'NAME_TYPE_SUITE',
                                                    'NAME_INCOME_TYPE',
                                                    'NAME_EDUCATION_TYPE',
                                                    'NAME_FAMILY_STATUS',
                                                    'NAME_HOUSING_TYPE']}